name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run update_readme.py
      run: |
        python update_readme.py
    - name: Update README.md file
      run: |
        git pull
        git add .
        git diff
        git config --local user.email "swhan9404@naver.com"
        git config --local user.name "bot"
        git commit -m "Update : $(expr $(date '+%Y-%m-%d')) README.md"
        git push
